<?php

namespace ContainerSsY701X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BKEorDsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BKEorDs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BKEorDs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'repository' => ['privates', 'App\\Repository\\SinistreRepository', 'getSinistreRepositoryService', true],
            's' => ['privates', '.errored..service_locator.BKEorDs.App\\Entity\\Sinistre', NULL, 'Cannot autowire service ".service_locator.BKEorDs": it references class "App\\Entity\\Sinistre" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'repository' => 'App\\Repository\\SinistreRepository',
            's' => 'App\\Entity\\Sinistre',
        ]);
    }
}
