<?php

namespace ContainerSsY701X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSinistreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BKEorDs.App\Entity\Sinistre' shared service.
     *
     * @return \App\Entity\Sinistre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.BKEorDs": it references class "App\\Entity\\Sinistre" but no such service exists.');
    }
}
