<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSLxJDkE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSLxJDkE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSLxJDkE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSLxJDkE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSLxJDkE\App_KernelDevDebugContainer([
    'container.build_hash' => 'SLxJDkE',
    'container.build_id' => '509d0409',
    'container.build_time' => 1678210425,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSLxJDkE');
